package br.com.chongroup.hestia.metamodel;

import java.util.ArrayList;
import java.util.List;

public class Function {
    protected int id;

    /** The name of the function can be repeated in the structure. For this, the code to be generated by the metamodel must ensure that the function name will be unique. */
    protected String name;

    protected String description;

    protected String dataType;

    protected List<Block> blocks;

    protected List<Parameter> parameters = new ArrayList<>();

    public Function() {

    }

    public Function(int id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;
    }

    public Function(int id, String name, String description, String dataType) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.dataType = dataType;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public List<Block> getBlocks() {
        return blocks;
    }

    public void setBlocks(List<Block> blocks) {
        this.blocks = blocks;
    }

    public List<Parameter> getParameters() {
        return parameters;
    }

    public void setParameters(List<Parameter> parameters) {
        this.parameters = parameters;
    }

}
